name: Publish

on:
  push:
    branches:    
      - master 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: "master"
    - uses: actions/checkout@v2
      with:
        repository: "huettner94/prb"
        ref: "gh-pages"
        path: "gh-pages"
    - name: Generate page
      run: |
        cd "${GITHUB_WORKSPACE}/master"
        pip install -r requirements.txt
        ./generator.py
        cp -R output/* "${GITHUB_WORKSPACE}/gh-pages/"
        cd "${GITHUB_WORKSPACE}/gh-pages/"
        git add .
        git config --global user.name "Github action"
        git config --global user.email "github-action@github.com"
        git commit -m "applied change"
    - name: Push pages
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        directory: gh-pages
